# Generated by Codex on 2026-06-16

from django.db import migrations, models


def mark_booked_slots(apps, schema_editor):
    LessonSlot = apps.get_model('home', 'LessonSlot')
    LessonSlot.objects.filter(student__isnull=False).update(status='booked')


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_lessonslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonslot',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('booked', 'Booked')], default='available', max_length=16),
        ),
        migrations.RunPython(mark_booked_slots, migrations.RunPython.noop),
    ]
