# Generated by Codex on 2026-06-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_lessonslot_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonslot',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('pending', 'Pending'), ('booked', 'Booked')], default='available', max_length=16),
        ),
    ]
